name: Release npminfo

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Downloading code from a repository
        uses: actions/checkout@v4

      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "26"

      - name: Install dependencies
        run: npm ci

      - name: Compiling and Packaging Binaries
        run: |
          # Linux x64 & ARM64
          npm run build && tar -czf npminfo-linux-x64.tar.gz -C ./build npminfo-linux
          npm run build-arm64 && tar -czf npminfo-linux-arm64.tar.gz -C ./build npminfo-linux-arm64

          # Windows x64 & ARM64
          npm run build:win && zip -j npminfo-win-x64.zip ./build/npminfo-win.exe
          npm run build:win-arm64 && zip -j npminfo-win-arm64.zip ./build/npminfo-win-arm64.exe

      - name: Publishing a release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            npminfo-linux-x64.tar.gz
            npminfo-linux-arm64.tar.gz
            npminfo-win-x64.zip
            npminfo-win-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
